# Generated by Django 5.1.15 on 2026-07-07 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Yo'nalish (dastur)",
                'verbose_name_plural': "Yo'nalishlar (dasturlar)",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('date_of_birth', models.DateField(verbose_name="Tug'ilgan sana")),
                ('passport_number', models.CharField(max_length=20, verbose_name='Passport raqami')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('passport_file', models.FileField(upload_to='documents/passport/', verbose_name='Passport')),
                ('diploma_transcript', models.FileField(blank=True, null=True, upload_to='documents/transcript/', verbose_name='Diplom ilovasi (magistratura uchun)')),
                ('school_certificate', models.FileField(upload_to='documents/certificate/', verbose_name='Attestat yoki diplom nusxasi')),
                ('photo', models.ImageField(upload_to='documents/photo/', verbose_name='Foto (3x4)')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='documents/extra_certificate/', verbose_name="Sertifikat (mavjud bo'lsa)")),
                ('unique_code', models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='Ariza kodi')),
                ('status', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('qabul_qilindi', 'Qabul qilindi'), ('rad_etildi', 'Rad etildi')], default='kutilmoqda', max_length=20, verbose_name='Holati')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.faculty', verbose_name='Fakultet')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.programme', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
